import "@github/markdown-toolbar-element";
import "@github/relative-time-element";
import "./_modules/audio-clipper";
import ClientTimezone from "./_modules/ClientTimezone";
import Clipboard from "./_modules/Clipboard";
import DateTimePicker from "./_modules/DateTimePicker";
import Dropdown from "./_modules/Dropdown";
import HotKeys from "./_modules/HotKeys";
import "./_modules/markdown-preview";
import "./_modules/markdown-write-preview";
import SelectMulti from "./_modules/SelectMulti";
import "./_modules/permalink-edit";
import "./_modules/play-soundbite";
import PublishMessageWarning from "./_modules/PublishMessageWarning";
import Select from "./_modules/Select";
import SidebarToggler from "./_modules/SidebarToggler";
import Slugify from "./_modules/Slugify";
import ThemePicker from "./_modules/ThemePicker";
import Time from "./_modules/Time";
import Tooltip from "./_modules/Tooltip";
import ValidateFileSize from "./_modules/ValidateFileSize";
import "./_modules/video-clip-previewer";
import VideoClipBuilder from "./_modules/VideoClipBuilder";
import "./_modules/code-editor";
import "@patternfly/elements/pf-tabs/pf-tabs.js";
import FieldArray from "./_modules/FieldArray";

Dropdown();
Tooltip();
Select();
SelectMulti();
Slugify();
SidebarToggler();
ClientTimezone();
DateTimePicker();
Time();
Clipboard();
ThemePicker();
PublishMessageWarning();
HotKeys();
ValidateFileSize();
VideoClipBuilder();
FieldArray();
