<?php

declare(strict_types=1);

/**
 * @icon('podcasting:amazon')
 * @icon('podcasting:antennapod')
 * @icon('podcasting:anytime')
 * @icon('podcasting:apple')
 * @icon('podcasting:blubrry')
 * @icon('podcasting:breez')
 * @icon('podcasting:castamatic')
 * @icon('podcasting:castbox')
 * @icon('podcasting:castopod')
 * @icon('podcasting:castro')
 * @icon('podcasting:deezer')
 * @icon('podcasting:episodes-fm')
 * @icon('podcasting:fountain')
 * @icon('podcasting:fyyd')
 * @icon('podcasting:gpodder')
 * @icon('podcasting:ivoox')
 * @icon('podcasting:listennotes')
 * @icon('podcasting:overcast')
 * @icon('podcasting:playerfm')
 * @icon('podcasting:plink')
 * @icon('podcasting:pocketcasts')
 * @icon('podcasting:podbean')
 * @icon('podcasting:podcastaddict')
 * @icon('podcasting:podcastguru')
 * @icon('podcasting:podcastindex')
 * @icon('podcasting:podchaser')
 * @icon('podcasting:podcloud')
 * @icon('podcasting:podfriend')
 * @icon('podcasting:podinstall')
 * @icon('podcasting:podlink')
 * @icon('podcasting:podlp')
 * @icon('podcasting:podnews')
 * @icon('podcasting:podtail')
 * @icon('podcasting:podverse')
 * @icon('podcasting:radiopublic')
 * @icon('podcasting:sphinxchat')
 * @icon('podcasting:spotify')
 * @icon('podcasting:spreaker')
 * @icon('podcasting:truefans')
 * @icon('podcasting:tsacdop')
 * @icon('podcasting:tunein')
 * @icon('podcasting:youtube-music')
 */
